/*

 MAP2.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 9 x 8
   Tile set      : tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 1
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define MAP2_DATAWidth 9
#define MAP2_DATAHeight 8
#define MAP2_DATABank 0

extern unsigned char MAP2_DATA[];

/* End of MAP2.H */
