/*

 MAP3.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 7 x 8
   Tile set      : tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 1
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define MAP3_DATAWidth 7
#define MAP3_DATAHeight 8
#define MAP3_DATABank 0

extern unsigned char MAP3_DATA[];

/* End of MAP3.H */
