/*

 MAPDATA.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 10 x 10
   Tile set      : C:\Users\Brand\Documents\Programming\LOZ (C, GB)\tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 1
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define MAP_DATAWidth 10
#define MAP_DATAHeight 10
#define MAP_DATABank 0

extern unsigned char MAP_DATA[];

/* End of MAPDATA.H */
